### ISSUE TITLE
No module named 'configreader'

### ISSUE THREAD

**Issue by jsotogaviard** [awslabs/collectd-cloudwatch#102]
I have installed collectd running ./setup.py with python 2.7.18
however the service is not able to start because of the error: No module named 'configreader'

here is the full stack trace
[2021-12-06 20:57:10] [error] ModuleNotFoundError: No module named 'configreader'
[2021-12-06 20:57:20] [info] plugin_load: plugin "cpu" successfully loaded.
[2021-12-06 20:57:20] [info] plugin_load: plugin "df" successfully loaded.
[2021-12-06 20:57:20] [info] plugin_load: plugin "memory" successfully loaded.
[2021-12-06 20:57:20] [info] plugin_load: plugin "swap" successfully loaded.
[2021-12-06 20:57:20] [info] plugin_load: plugin "python" successfully loaded.
[2021-12-06 20:57:20] [error] python plugin: Error importing module "cloudwatch_writer".
[2021-12-06 20:57:20] [error] Unhandled python exception in importing module: ModuleNotFoundError: No module named 'configreader'
[2021-12-06 20:57:20] [error] Traceback (most recent call last):
[2021-12-06 20:57:20] [error]   File "/opt/collectd-plugins/cloudwatch_writer.py", line 12, in <module>
    from cloudwatch.modules.configuration.confighelper import ConfigHelper
[2021-12-06 20:57:20] [error]   File "/opt/collectd-plugins/cloudwatch/modules/configuration/confighelper.py", line 3, in <module>
    from configreader import ConfigReader
[2021-12-06 20:57:20] [error] ModuleNotFoundError: No module named 'configreader'

**Comment by jsotogaviard** [comment]
what the is the required version of python to run it ?

**Comment by Suhan777** [comment]
Any idea on how to get around this? Experiencing the same issue
