### ISSUE TITLE
support for openSUSE

### ISSUE THREAD

**Issue by esara** [awslabs/collectd-cloudwatch#26]
thanks for the cloudwatch plugin, but the setup.py does not work with openSUSE
/home/ec2-user/collectd-cloudwatch/src # ./setup.py 
Traceback (most recent call last):
  File "./setup.py", line 586, in <module>
    main()
  File "./setup.py", line 579, in main
    install_plugin()
  File "./setup.py", line 497, in install_plugin
    install_packages(SYSTEM_DEPENDENCIES)
  File "./setup.py", line 253, in install_packages
    command = DISTRIBUTION_TO_INSTALLER[detect_linux_distribution()] + " ".join(packages)
KeyError: 'openSUSE\nVERSION'

Can we add support?

**Comment by esara** [comment]
After https://github.com/turbonomic/collectd-cloudwatch/commit/b871b993ef61f9dcc9ab0df94425dab15dfeffcc, it runs fine on openSUSE, too

home/ec2-user/collectd-cloudwatch/src # ./setup.py 
Installing dependencies ... OK
Installing python dependencies ... OK
Downloading plugin ... OK
Extracting plugin ... OK
Moving to collectd plugins directory ... OK
Copying CloudWatch plugin include file ... OK

Choose AWS region for published metrics:
  1. Automatic [us-east-1]
  2. Custom
Enter choice [1]: 

Choose hostname for published metrics:
  1. EC2 instance id [i-f552a16d]
  2. Custom
Enter choice [1]: 

IAM Role could not be automatically detected.
Enter absolute path to AWS credentials file [/root/.aws/credentials]: 
Enter access key: XXX 
Enter secret key: YYY

Choose how to install CloudWatch plugin in collectd:
  1. Do not modify existing collectd configuration
  2. Add plugin to the existing configuration
Enter choice [2]: 
Plugin configuration written successfully.
Credentials configuration written successfully.
Stopping collectd process ... NOT OK
Starting collectd process … OK
