### ISSUE TITLE
setup.py is failing due to RegEx issue

### ISSUE THREAD

**Issue by samansad** [awslabs/collectd-cloudwatch#90]
I am running the setup.py with Python 2.7 on EC2 R4 RedHat 6 and getting the following error. There are 3 files that this RegEx is reading ('/etc/system-release', '/etc/redhat-release', '/etc/lsb-release'). However, non of these files contains "NAME=" which the regex  is looking for. Do I need to add anything to any of these files? Am I missing any prerequisite? 

I have installed Collectd version is 5.5.3.1.

root@EC2[ss] python2.7 setup.py
Traceback (most recent call last):
  File "setup.py", line 966, in <module>
    main()
  File "setup.py", line 959, in main
    install_plugin()
  File "setup.py", line 871, in install_plugin
    install_packages(SYSTEM_DEPENDENCIES)
  File "setup.py", line 263, in install_packages
    command = DISTRIBUTION_TO_INSTALLER[detect_linux_distribution()] + " ".join(packages)
  File "setup.py", line 272, in detect_linux_distribution
    return DISTRO_NAME_REGEX.search(search_string).group(1).strip()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by samansad** [comment]
Ok I found the issue. For RedHat 6 there is no os-release and redhat-release does not follow the format that this python code is expecting to see. To solve this, I manually made the os-release and added "NAME= "Red Hat Enterprise Linux Server"" to it.
